DEFAULT_CONTEXT_MESSAGES = 20
DEFAULT_MAX_COMPLETION_TOKENS = 1024
DEFAULT_STATE_PATH = ".mnemos/state.db"
DEFAULT_TEMPERATURE = 0.7

ENV_OPENAI_BASE_URL = "OPENAI_BASE_URL"
ENV_OPENAI_API_KEY = "OPENAI_API_KEY"
ENV_OPENAI_DEFAULT_MODEL = "OPENAI_DEFAULT_MODEL"
ENV_DISCORD_GUILD_ID = "DISCORD_GUILD_ID"
ENV_DISCORD_TOKEN = "DISCORD_TOKEN"
ENV_EXA_API_KEY = "EXA_API_KEY"
ENV_MAX_COMPLETION_TOKENS = "MAX_COMPLETION_TOKENS"
ENV_MAX_CONTEXT_MESSAGES = "MAX_CONTEXT_MESSAGES"
ENV_MNEMOS_ADMIN_USER_IDS = "MNEMOS_ADMIN_USER_IDS"
ENV_MNEMOS_ALLOW_DISCORD_ADMINS = "MNEMOS_ALLOW_DISCORD_ADMINS"
ENV_MNEMOS_STATE_PATH = "MNEMOS_STATE_PATH"
ENV_TEMPERATURE = "TEMPERATURE"
