DEFAULT_CONTEXT_MESSAGES = 20
DEFAULT_INFERENCE_URL = "https://inference.do-ai.run"
DEFAULT_MAX_COMPLETION_TOKENS = 1024
DEFAULT_MODEL = "kimi-k2.6"
DEFAULT_STATE_PATH = ".mnemos/state.db"
DEFAULT_TEMPERATURE = 0.7

ENV_DIGITALOCEAN_INFERENCE_URL = "DIGITALOCEAN_INFERENCE_URL"
ENV_DIGITALOCEAN_MODEL_ACCESS_KEY = "DIGITALOCEAN_MODEL_ACCESS_KEY"
ENV_DIGITALOCEAN_DEFAULT_MODEL = "DIGITALOCEAN_DEFAULT_MODEL"
ENV_DISCORD_GUILD_ID = "DISCORD_GUILD_ID"
ENV_DISCORD_TOKEN = "DISCORD_TOKEN"
ENV_MAX_COMPLETION_TOKENS = "MAX_COMPLETION_TOKENS"
ENV_MAX_CONTEXT_MESSAGES = "MAX_CONTEXT_MESSAGES"
ENV_MNEMOS_ADMIN_USER_IDS = "MNEMOS_ADMIN_USER_IDS"
ENV_MNEMOS_ALLOW_DISCORD_ADMINS = "MNEMOS_ALLOW_DISCORD_ADMINS"
ENV_MNEMOS_STATE_PATH = "MNEMOS_STATE_PATH"
ENV_TEMPERATURE = "TEMPERATURE"
